services:
  noreco_power_outage:
    container_name: noreco_power_outage
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Manila
    volumes:
      - ./.env:/app/.env:ro
      - noreco_images_data:/app/images  # сохраняем папку images между перезапусками
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  noreco_images_data:
